### ISSUE TITLE
Rename PyPi client

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#55]
Current name: https://pypi.org/project/nlp-sandbox-client/
New name should be: https://pypi.org/project/nlpsandbox-client/

**Comment by tschaffter** [comment]
I'm trying to reproduce what I did initially: push the package to PyPi manually using my account, then adding the service user as a member of the package so that it can push the package to PyPi during CI/CD workflow.

I have an issue pushing manually to PyPi using [these instructions (twine)](https://twine.readthedocs.io/en/latest/).

```
$ conda create --name pypi python=3.8
$ conda activate pypi
$ pip install twine
$ python setup.py sdist bdist_wheel
running sdist
running egg_info
writing nlpsandbox_client.egg-info/PKG-INFO
writing dependency_links to nlpsandbox_client.egg-info/dependency_links.txt
writing entry points to nlpsandbox_client.egg-info/entry_points.txt
writing requirements to nlpsandbox_client.egg-info/requires.txt
writing top-level names to nlpsandbox_client.egg-info/top_level.txt
reading manifest file 'nlpsandbox_client.egg-info/SOURCES.txt'
writing manifest file 'nlpsandbox_client.egg-info/SOURCES.txt'
running check
creating nlpsandbox-client-0.2.0
creating nlpsandbox-client-0.2.0/nlpsandbox_client.egg-info
creating nlpsandbox-client-0.2.0/nlpsandboxclient
creating nlpsandbox-client-0.2.0/nlpsandboxclient/cli
creating nlpsandbox-client-0.2.0/nlpsandboxclient/datanode
creating nlpsandbox-client-0.2.0/nlpsandboxclient/user
copying files to nlpsandbox-client-0.2.0...
copying README.md -> nlpsandbox-client-0.2.0
copying setup.cfg -> nlpsandbox-client-0.2.0
copying setup.py -> nlpsandbox-client-0.2.0
copying nlpsandbox_client.egg-info/PKG-INFO -> nlpsandbox-client-0.2.0/nlpsandbox_client.egg-info
copying nlpsandbox_client.egg-info/SOURCES.txt -> nlpsandbox-client-0.2.0/nlpsandbox_client.egg-info
copying nlpsandbox_client.egg-info/dependency_links.txt -> nlpsandbox-client-0.2.0/nlpsandbox_client.egg-info
copying nlpsandbox_client.egg-info/entry_points.txt -> nlpsandbox-client-0.2.0/nlpsandbox_client.egg-info
copying nlpsandbox_client.egg-info/requires.txt -> nlpsandbox-client-0.2.0/nlpsandbox_client.egg-info
copying nlpsandbox_client.egg-info/top_level.txt -> nlpsandbox-client-0.2.0/nlpsandbox_client.egg-info
copying nlpsandboxclient/__init__.py -> nlpsandbox-client-0.2.0/nlpsandboxclient
copying nlpsandboxclient/api_client.py -> nlpsandbox-client-0.2.0/nlpsandboxclient
copying nlpsandboxclient/client.py -> nlpsandbox-client-0.2.0/nlpsandboxclient
copying nlpsandboxclient/evaluation.py -> nlpsandbox-client-0.2.0/nlpsandboxclient
copying nlpsandboxclient/utils.py -> nlpsandbox-client-0.2.0/nlpsandboxclient
copying nlpsandboxclient/validation.py -> nlpsandbox-client-0.2.0/nlpsandboxclient
copying nlpsandboxclient/cli/__init__.py -> nlpsandbox-client-0.2.0/nlpsandboxclient/cli
copying nlpsandboxclient/cli/__main__.py -> nlpsandbox-client-0.2.0/nlpsandboxclient/cli
copying nlpsandboxclient/cli/community.py -> nlpsandbox-client-0.2.0/nlpsandboxclient/cli
copying nlpsandboxclient/cli/evaluate.py -> nlpsandbox-client-0.2.0/nlpsandboxclient/cli
copying nlpsandboxclient/cli/validate.py -> nlpsandbox-client-0.2.0/nlpsandboxclient/cli
copying nlpsandboxclient/datanode/__init__.py -> nlpsandbox-client-0.2.0/nlpsandboxclient/datanode
copying nlpsandboxclient/datanode/models.py -> nlpsandbox-client-0.2.0/nlpsandboxclient/datanode
copying nlpsandboxclient/user/__init__.py -> nlpsandbox-client-0.2.0/nlpsandboxclient/user
copying nlpsandboxclient/user/user.py -> nlpsandbox-client-0.2.0/nlpsandboxclient/user
Writing nlpsandbox-client-0.2.0/setup.cfg
Creating tar archive
removing 'nlpsandbox-client-0.2.0' (and everything under it)
running bdist_wheel
running build
running build_py
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/nlpsandboxclient
copying build/lib/nlpsandboxclient/api_client.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient
creating build/bdist.linux-x86_64/wheel/nlpsandboxclient/cli
copying build/lib/nlpsandboxclient/cli/community.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient/cli
copying build/lib/nlpsandboxclient/cli/evaluate.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient/cli
copying build/lib/nlpsandboxclient/cli/validate.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient/cli
copying build/lib/nlpsandboxclient/cli/__init__.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient/cli
copying build/lib/nlpsandboxclient/cli/__main__.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient/cli
copying build/lib/nlpsandboxclient/client.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient
creating build/bdist.linux-x86_64/wheel/nlpsandboxclient/datanode
copying build/lib/nlpsandboxclient/datanode/models.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient/datanode
copying build/lib/nlpsandboxclient/datanode/__init__.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient/datanode
copying build/lib/nlpsandboxclient/evaluation.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient
creating build/bdist.linux-x86_64/wheel/nlpsandboxclient/user
copying build/lib/nlpsandboxclient/user/user.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient/user
copying build/lib/nlpsandboxclient/user/__init__.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient/user
copying build/lib/nlpsandboxclient/utils.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient
copying build/lib/nlpsandboxclient/validation.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient
copying build/lib/nlpsandboxclient/__init__.py -> build/bdist.linux-x86_64/wheel/nlpsandboxclient
running install_egg_info
Copying nlpsandbox_client.egg-info to build/bdist.linux-x86_64/wheel/nlpsandbox_client-0.2.0-py3.8.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/nlpsandbox_client-0.2.0.dist-info/WHEEL
creating 'dist/nlpsandbox_client-0.2.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'nlpsandboxclient/__init__.py'
adding 'nlpsandboxclient/api_client.py'
adding 'nlpsandboxclient/client.py'
adding 'nlpsandboxclient/evaluation.py'
adding 'nlpsandboxclient/utils.py'
adding 'nlpsandboxclient/validation.py'
adding 'nlpsandboxclient/cli/__init__.py'
adding 'nlpsandboxclient/cli/__main__.py'
adding 'nlpsandboxclient/cli/community.py'
adding 'nlpsandboxclient/cli/evaluate.py'
adding 'nlpsandboxclient/cli/validate.py'
adding 'nlpsandboxclient/datanode/__init__.py'
adding 'nlpsandboxclient/datanode/models.py'
adding 'nlpsandboxclient/user/__init__.py'
adding 'nlpsandboxclient/user/user.py'
adding 'nlpsandbox_client-0.2.0.dist-info/LICENSE'
adding 'nlpsandbox_client-0.2.0.dist-info/METADATA'
adding 'nlpsandbox_client-0.2.0.dist-info/WHEEL'
adding 'nlpsandbox_client-0.2.0.dist-info/entry_points.txt'
adding 'nlpsandbox_client-0.2.0.dist-info/top_level.txt'
adding 'nlpsandbox_client-0.2.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
```

Then

```
$ twine upload -r testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Traceback (most recent call last):
  File "/home/tschaffter/.conda/envs/pypi/bin/twine", line 8, in <module>
    sys.exit(main())
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/twine/__main__.py", line 28, in main
    result = cli.dispatch(sys.argv[1:])
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/twine/cli.py", line 82, in dispatch
    return main(args.args)
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/twine/commands/upload.py", line 151, in main
    return upload(upload_settings, parsed_args.dists)
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/twine/commands/upload.py", line 85, in upload
    packages_to_upload = [
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/twine/commands/upload.py", line 86, in <listcomp>
    _make_package(filename, signatures, upload_settings) for filename in uploads
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/twine/commands/upload.py", line 58, in _make_package
    package = package_file.PackageFile.from_filename(filename, upload_settings.comment)
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/twine/package.py", line 84, in from_filename
    meta = DIST_TYPES[dtype](filename)
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/twine/wininst.py", line 17, in __init__
    self.extractMetadata()
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/pkginfo/distribution.py", line 108, in extractMetadata
    data = self.read()
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/site-packages/twine/wininst.py", line 33, in read
    archive = zipfile.ZipFile(fqn)
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/home/tschaffter/.conda/envs/pypi/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by tschaffter** [comment]
```
$ pip freeze
attrs==20.2.0
bleach==3.2.1
certifi==2020.11.8
cffi==1.14.4
chardet==3.0.4
click==7.1.2
clickclick==1.2.2
colorama==0.4.4
cryptography==3.2.1
docutils==0.16
flake8==3.8.4
Flask==1.1.2
idna==2.10
importlib-metadata==1.7.0
inflection==0.5.1
itsdangerous==1.1.0
jeepney==0.6.0
Jinja2==2.11.2
jsonschema==3.2.0
keyring==21.5.0
MarkupSafe==1.1.1
mccabe==0.6.1
openapi-spec-validator==0.2.9
packaging==20.7
pkginfo==1.6.1
pycodestyle==2.6.0
pycparser==2.20
pyflakes==2.2.0
Pygments==2.7.2
pyparsing==2.4.7
pyrsistent==0.17.3
PyYAML==5.3.1
readme-renderer==28.0
requests==2.25.0
requests-toolbelt==0.9.1
rfc3986==1.4.0
SecretStorage==3.3.0
six==1.15.0
tqdm==4.54.0
twine==3.2.0
urllib3==1.26.2
webencodings==0.5.1
Werkzeug==1.0.1
zipp==3.1.0
```

**Comment by tschaffter** [comment]
Here is [another tutorial](https://thucnc.medium.com/how-to-publish-your-own-python-package-to-pypi-4318868210f9). Same error.

**Comment by tschaffter** [comment]
The above error is thrown on Win using WSL Debian. I was able to run the above command and publish the package from a Docker container running Debian.

```
$ twine upload dist/*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: tschaffter
/home/ubuntu/anaconda3/envs/pypi/lib/python3.8/site-packages/twine/auth.py:72: UserWarning: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
  warnings.warn(str(exc))
Enter your password:
Uploading nlpsandbox_client-0.2.0-py3-none-any.whl
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21.4k/21.4k [00:01<00:00, 20.2kB/s]
Uploading nlpsandbox-client-0.2.0.tar.gz
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14.9k/14.9k [00:00<00:00, 18.4kB/s]

View at:
https://pypi.org/project/nlpsandbox-client/0.2.0/
```

https://pypi.org/project/nlpsandbox-client/

Publishing to PyPi worked but not to testpypi:

```
$ twine upload -r testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: tschaffter
/home/ubuntu/anaconda3/envs/pypi/lib/python3.8/site-packages/twine/auth.py:72: UserWarning: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
  warnings.warn(str(exc))
Enter your password:
Uploading nlpsandbox_client-0.2.0-py3-none-any.whl
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21.4k/21.4k [00:00<00:00, 128kB/s]
NOTE: Try --verbose to see response content.
HTTPError: 403 Forbidden from https://test.pypi.org/legacy/
Invalid or non-existent authentication information. See https://test.pypi.org/help/#invalid-auth for more information.
```

**Comment by tschaffter** [comment]
I created the GH release 0.2.1 to test the publication to PyPi in the CI/CD workflow. However the publication failed, see https://github.com/nlpsandbox/nlpsandbox-client/actions/runs/394290232.

@thomasyu888 Can you please have a look at this?

**Comment by tschaffter** [comment]
I deleted the old PyPi package "nlp-sandbox-client"

**Comment by tschaffter** [comment]
The issue was because the previous token had its scope limited to the old pypi package nlp-sandbox-client.
