### ISSUE TITLE
Evaluation on 2014-i2b2-20201203 evaluation dataset fails.

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-client#77]
```
# assumes synapseclient and nlpsandbox-client installed locally
synapse get -r syn23628905
nlp-cli evaluate prediction --pred_filepath converted_pred.json --gold_filepath converted_gold.json --eval_type date

instance                 F1             Precision      Recall              
---------------------------------------------------------------------------
relax                    0.25           0.26           0.25                


instance                 F1             Precision      Recall              
---------------------------------------------------------------------------
strict                   0.25           0.26           0.25                


Traceback (most recent call last):
  File "/Users/tyu/anaconda3/envs/nlp-client/bin/nlp-cli", line 33, in <module>
    sys.exit(load_entry_point('nlpsandbox-client', 'console_scripts', 'nlp-cli')())
  File "/Users/tyu/sage/nlp/nlp-sandbox-client/nlpsandboxclient/cli/__main__.py", line 15, in main
    cli()
  File "/Users/tyu/anaconda3/envs/nlp-client/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/tyu/anaconda3/envs/nlp-client/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/tyu/anaconda3/envs/nlp-client/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tyu/anaconda3/envs/nlp-client/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tyu/anaconda3/envs/nlp-client/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tyu/anaconda3/envs/nlp-client/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/tyu/sage/nlp/nlp-sandbox-client/nlpsandboxclient/cli/evaluate.py", line 34, in evaluate_prediction
    results = evaluator.eval()
  File "/Users/tyu/sage/nlp/nlp-sandbox-client/nlpsandboxclient/evaluation.py", line 80, in eval
    self.eval_category_instance()
  File "/Users/tyu/sage/nlp/nlp-sandbox-client/nlpsandboxclient/evaluation.py", line 147, in eval_category_instance
    self.print_out(tp, fp, fn, self.evaluation_type, "strict")
  File "/Users/tyu/sage/nlp/nlp-sandbox-client/nlpsandboxclient/evaluation.py", line 182, in print_out
    F1 = round(2 * ((precision * recall) / (precision + recall)), 2)
ZeroDivisionError: float division by zero



```

**Comment by thomasyu888** [comment]
To reproduce: 

```
# assumes synapseclient and nlpsandbox-client installed locally
synapse get -r syn23628905
nlp-cli evaluate prediction --pred_filepath converted_pred.json --gold_filepath converted_gold.json --eval_type date
```

**Comment by tschaffter** [comment]
@yy6linda Can you fix this division by zero?

**Comment by yy6linda** [comment]
Yes I will, can I have the example annotation that generated this error?

**Comment by thomasyu888** [comment]
@yy6linda There is the a synapse id in the code above - Here is the link https://www.synapse.org/#!Synapse:syn23628905
